### ISSUE TITLE
popper: implement resource/performance monitoring

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/malacology-popper#16]
We need to collect important metrics (e.g., CPU utilization, network traffic, etc.) for all nodes on our cluster. To do this, we have 2 options:
- `collectd` on each node to monitor and `graphite` to push all measurements to 1 node
- `collectl` on each node to monitor and `ansible` to push all measurements to 1 node

**Comment by michaelsevilla** [comment]
Addressed with a new role called `monitor` in #18. This role launches `collectl` on all worker nodes and `graphite` on the head node for visualization and metric collection. For more details, see the corresponding commit [7b8f422](https://github.com/systemslab/srl-roles/commit/7b8f4227108552e523df145458de2eceb9bc98b4) in srl-roles.

**Comment by ivotron** [comment]
this is really cool

**Comment by ivotron** [comment]
should we also look at storing the results in a timeseries db? We could make those results be part of the experiment. Also, does `collectl` know about containers (i.e. display stats on per-container or per-host)?

**Comment by michaelsevilla** [comment]
When `graphite` receives metric measurements from `collectl` on remote nodes, it stores them in a [WhisperDB](https://github.com/graphite-project/whisper). Anecdotally, for a 30 minute job (where I compiled Ceph), the database files (e.g., cpu.wsp, io.wsp, etc.) grew to about a total of 2MB. 

`collectl` does _not_ know about containers but `graphite` can receive metrics from a lot of tools ([listed here](http://graphite.readthedocs.org/en/latest/tools.html)). It can also receive plain text, so we could write a bash script that sends data to graphite, something like:

```
while 1; do
  docker stats mycontainer | formatter.py | netcat graphite-server.soe.ucsc.edu
done
```

**Comment by ivotron** [comment]
Cool! IMO that would be enough (whisperdb). For per-container stats, I think we're also OK (at least as of today) since we run our experiments in isolation, i.e. no other thing running on our hosts.
