### ISSUE TITLE
Add discussion about Zookeeper as a bolt-on service

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/malacology-popper#25]
Compare/Contrast implementing sequencer on Zookeeper.
- we can create stuff that is not durable in Ceph
- traditionally, stuff in storage systems is assumed durable

We need to show that object classes solve a specific problem.

Use case: implement zlog with a proxy
1. serialize over the metdata server
2. interpose a new layer (like proxy) to do pipelining
- the only way to do that in Ceph is with an IO
- even with the same optimizations (e..g, batch up the IOs), what kind of performance hit do we get?
- we would see that you need an entire networking and transactions stack; you would have to use the object interface on the OSD level -- you can't use any of the object classes
- is this even possible? Best case scenario: prove that it is impossible

References: Neha's HDFS HA namenode example

**Comment by michaelsevilla** [comment]
Zookeeper is persistent but the sequence is in memory and volatile... so we enable scalability by explicitly setting it as not-persistent. This goes against traditional storage meanings.

**Comment by neha-ojha** [comment]
HDFS HA namenode example
[section 2: Background]  M. Balakrishnan et al. Tango: Distributed data structures over a shared log. In SOSP ’13, Farmington, PA, November 3-6 2013.

**Comment by michaelsevilla** [comment]
Fixed by #31.
