### ISSUE TITLE
mantle: benchmark FileBench

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/malacology-popper#3]
The CMU teams uses YCSB to compare IndexFS and ShardFS in their [SoCC'16 paper](http://acmsocc.github.io/2015/accepted-papers.html). IndexFS/ShardFS is layered on top of HDFS, so it looks like they bring up an entire cloud stack (YCSB, talking to HBASE, talking to HDFS). Unfortunately, for their numbers they rely heavily on [YCSB++](http://www.pdl.cmu.edu/ycsb++/), a set of extensions they wrote that give YCSB more functionality and they don't specify how the knobs are turned or what values they used to turn them.

**Comment by dotnwat** [comment]
Change this to FileBench @michaelsevilla

**Comment by ivotron** [comment]
coincidentally, I just created an automated build for filebench. https://github.com/ivotron/docker-filebench . It still needs to be documented. Can we work on this automated build so that we collectively benefit?

**Comment by michaelsevilla** [comment]
I think we decided that using Mantle to find the best policy for different workloads is beyond the scope of our "programmability" argument. Showing the best balancer for two workloads (e.g., FileBench and OpenSSL compile) is a weak evaluation and seems to be stealing the contribution of the SC paper (i.e., we aren't contributing anything new). This deserves more attention as another paper where we test A LOT of benchmarks (like CMU papers) and where "load balancing" is the focus of the paper instead of "programmability". We are going to focus our efforts on merging Mantle and ZLog.
