### ISSUE TITLE
popper: add site Ansible code to deploy different Ceph backends 

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/malacology-popper#37]
We want to be able to slide different back-ends into Ceph:
- [ ] `site-ext4.yml` with SSD as the journal

**Comment by ivotron** [comment]
do you plan to add comparisons on these? If not, I'd leave this as an optional thing. If `ext4` works fine, then we can leave `xfs` and `bluestore` for later.

**Comment by michaelsevilla** [comment]
Agreed. Let's just get the journal working. `ext4` on the 3 disks and one journal on the SSD. I'm going to move forward with Mantle stuff while you take a look at this.
