### ISSUE TITLE
Need to consume sausages at noon.

### ISSUE THREAD

**Issue by carlosmalt** [michaelsevilla/malacology-popper#45]
I will grill some sausage and bring them to the lab at noon. I will also bring two kinds of sauerkraut and mustard. How many people?

**Comment by michaelsevilla** [comment]
Thanks. Ivo and I are coming in at 10.

**Comment by dotnwat** [comment]
Me too.

**Comment by ivotron** [comment]
Thanks!

**Comment by dotnwat** [comment]
Thanks for those sausages. So good
