### ISSUE TITLE
paper: emphasize programmability vs mere software reuse

### ISSUE THREAD

**Issue by carlosmalt** [michaelsevilla/malacology-popper#48]
Throughout the paper we need to make sure to emphasize that what we call "programmability" is not just mere refactoring of existing software. Turn statements like "re-using subsystem X" into something along the lines of "making subsystem X programmable by adding an API for policies".

**Comment by michaelsevilla** [comment]
Addressed in 575c91015a489369afb161e4d0ae7b633b5f06cd.
